
import AuthProviderContext from "@/AuthProviderContext/AuthProviderContext";
import ClientLayout from "./ClientLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProviderContext>
      <ClientLayout>{children}</ClientLayout>
    </AuthProviderContext>
  );
}
